export type ReelTemplate = "problem" | "before-after" | "mechanism" | "offer";

export type SocialContent = {
  day: number;
  slug: string;
  service: string;
  objective: "reach" | "trust" | "save" | "lead";
  template: ReelTemplate;
  hook: string;
  hookVariants?: [string, string, string];
  kicker: string;
  proof: string;
  cta: string;
  caption: string;
  voiceover: string;
  visualDirection: string;
  asset: string;
  paid?: boolean;
  durationInSeconds: number;
};

const content = (
  day: number,
  slug: string,
  service: string,
  objective: SocialContent["objective"],
  template: ReelTemplate,
  hook: string,
  kicker: string,
  proof: string,
  cta: string,
  asset: string,
  durationInSeconds: number,
  voiceover: string,
  caption: string,
  visualDirection: string,
  extra: Pick<SocialContent, "paid" | "hookVariants"> = {},
): SocialContent => ({day, slug, service, objective, template, hook, kicker, proof, cta, asset, durationInSeconds, voiceover, caption, visualDirection, ...extra});

export const socialContent: SocialContent[] = [
  content(1,"pencere-huzuru","Sineklik","reach","problem","KAPI AÇILINCA EVİN HUZURU DA KAÇIYORSA…","AÇIK KAPI","Temiz hava içeride. Sinekler dışarıda.","MODELİ İNCELE","products/lifestyle-kapi-plise.jpg",15,"Kapıyı açmak ferahlık getirmeli, sinek değil. Açıklığa göre ölçülen plise sistem, kullanılmadığında kenarda toplanır ve günlük geçişi kolaylaştırır.","Kapıyı açmaktan vazgeçmeyin. Açıklığınıza uygun sineklik modelini birlikte seçelim.","Açık balkon kapısı, görünür dış ortam ve plise tül aynı karede; hava akışını yalnız gerçek açıklıkla anlat."),
  content(2,"kapiya-yanlis-model","Sineklik","save","problem","BU KAPIYA PENCERE SİNEKLİĞİ TAKARSANIZ NE OLUR?","YANLIŞ SEÇİM","Geçiş sıklığı, açıklık ve kanat hareketi birlikte düşünülür.","KAYDET","products/pliseli-kapi-ref2.webp",24,"Kapı ve pencere aynı şekilde kullanılmaz. Sık geçilen bir kapıda açıklık genişliği, alt kılavuz ve açılma yönü doğru model seçimini belirler.","Kapı için model seçerken yalnız ölçüye bakmayın. Bu üç ayrıntıyı keşifte kontrol ediyoruz.","Kapı geçişini, alt kılavuzu ve katlanan tülü üç ayrı yakın planda göster."),
  content(3,"balkon-yanlis-kullanim","Cam Balkon","reach","before-after","BALKONUNUZ KÜÇÜK DEĞİL. YANLIŞ KULLANILIYOR OLABİLİR.","DÖNÜŞÜM","Açılır sistemle alanı gerektiğinde koruyun, gerektiğinde tamamen açın.","FOTOĞRAF GÖNDER","services/lifestyle/balkon-yasam-01.jpg",18,"Balkonun ölçüsü değişmedi. Kullanım biçimi değişti. Doğru açılım yönü ve cam sistemiyle alanı hava koşullarına göre yönetebilirsiniz.","Balkonunuzu kapatmadan önce nasıl kullanmak istediğinizi konuşalım. Bir fotoğraf ilk değerlendirme için yeterli.","Aynı açıdan boş ve düzenlenmiş balkon; sert bir dikey wipe ile dönüşüm."),
  content(4,"olcu-hatasi","Tüm Hizmetler","save","mechanism","BU ÖLÇÜ HATASI SİSTEMİ DE FİYATI DA DEĞİŞTİRİR.","ÖLÇÜ","Tek noktadan değil; üst, orta ve alttan kontrol.","KAYDET","cat-outdoor-visuals/09-kesif-ve-olcu-hizmeti.png",24,"Duvar ve doğramalar her zaman tam paralel olmayabilir. Bu nedenle açıklığı tek noktadan ölçmek yerine üstten, ortadan ve alttan kontrol ederiz.","Ön değerlendirme için yaklaşık ölçü yeterli. Üretimden önce ölçünün doğrulanması gerekir.","Metreyi tutan eller; üç ölçü noktasını turkuaz teknik çizgilerle işaretle."),
  content(5,"tek-hareket-plise","Sineklik","reach","mechanism","TEK HAREKET. AÇIK GEÇİŞ. SİNEKSİZ EV.","MEKANİZMA","Plise tül kenarda kompakt biçimde toplanır.","TEKLİF OLUŞTUR","products/pliseli-kapi-ref.webp",12,"Plise sineklik tek hareketle açılır, kenarda toplanır ve kapı geçişini yeniden serbest bırakır. Model, açıklığın ölçüsüne göre hazırlanır.","Nasıl çalıştığını görün; ölçünüze göre ön teklifinizi oluşturun.","Elin ürünü açıp kapattığı tek kesintisiz hareket; ray ve tutamak yakın planı."),
  content(6,"reklam-hava-girsin","Sineklik","lead","offer","HAVA GİRSİN. SİNEK GİRMESİN.","ÖLÇÜYE ÖZEL","Kapı ve pencerenize uygun plise, sürme, menteşeli veya duble seçenek.","HEMEN TEKLİF AL","products/lifestyle-kapi-plise.jpg",15,"Pencerenizi ve balkon kapınızı rahatça açın. Alanınıza göre ölçülen sineklik seçenekleri için ölçünüzü girin, yaklaşık teklifinizi oluşturun.","İstanbul’da ölçüye özel sineklik. Ölçünüzü girin, yaklaşık teklifinizi alın.","İlk karede açılan kapı; ikinci karede tülün kapanışı; finalde teklif ekranı.",{paid:true,hookVariants:["HAVA GİRSİN. SİNEK GİRMESİN.","PENCEREYİ AÇMAKTAN VAZGEÇMEYİN.","TEMİZ HAVA İÇERİ. SİNEKLER DIŞARI."]}),
  content(7,"profil-tek-basina-yetmez","PVC","trust","problem","PVC PROFİL TEK BAŞINA YALITIM SAĞLAMAZ.","USTA NOTU","Cam paketi, conta, aksesuar, ölçü ve montaj birlikte çalışır.","DETAYI ÖĞREN","services/pvc-kapi-pencere-v2.webp",28,"İyi bir PVC pencere yalnız profil markasından ibaret değildir. Cam paketi, conta, aksesuar ayarı ve montaj boşluklarının doğru kapatılması birlikte değerlendirilmelidir.","PVC seçerken yalnız profil sormayın. Sistemin tamamını değerlendirin.","Profil kesiti, cam kenarı, conta ve montaj birleşimini sırayla makro çekimle göster."),
  content(8,"cift-acilim-surme","PVC","save","mechanism","ÇİFT AÇILIM MI, SÜRME Mİ? ODANIZ KARAR VERİR.","SİSTEM SEÇİMİ","Havalandırma, mobilya ve geçiş alanı seçimde belirleyicidir.","KAYDET","services/pvc-kapi-pencere-v1.webp",25,"Her odada aynı pencere sistemi doğru değildir. Günlük havalandırma, perde ve mobilya yerleşimi ile geçiş ihtiyacı birlikte düşünülmelidir.","Karar vermeden önce kullanım biçiminizi belirleyin. Alanı birlikte değerlendirebiliriz.","Ekranı ikiye böl; çift açılım hareketi ile sürme hareketini sade ikonlarla karşılaştır."),
  content(9,"usta-olcu-kontrolu","Sineklik","trust","mechanism","USTA ÖLÇÜ ALIRKEN NEDEN ÜÇ NOKTAYI KONTROL EDİYOR?","SAHADAN","Paralellik, net açıklık ve montaj yüzeyi.","KAYDET","cat-outdoor-visuals/09-kesif-ve-olcu-hizmeti.png",25,"Üst, orta ve alt ölçüler arasındaki fark bize açıklığın paralelliğini gösterir. Montaj yüzeyi ve hareket alanı da aynı anda kontrol edilir.","Doğru ürün, doğru ölçüyle başlar. Bu videoyu ölçü alırken kullanmak için kaydedin.","Yüz göstermeden ölçü alan eller; her kontrolde sayısal işaret ve kısa saha sesi."),
  content(10,"eski-pvc-yenileme","PVC","trust","before-after","ESKİ DOĞRAMA DEĞİŞİNCE YALNIZ GÖRÜNTÜ DEĞİŞMEZ.","YENİLEME","Açılım, cam, conta ve montaj koşulları yeniden planlanır.","FOTOĞRAF GÖNDER","services/pvc-kapi-pencere-v2.webp",20,"PVC yenilemede yalnız eski çerçeveyi söküp yenisini takmıyoruz. Açılım yönünü, cam seçimini ve montaj yüzeyini yeniden değerlendiriyoruz.","Mevcut pencerenizin içten ve dıştan fotoğrafını gönderin; ilk değerlendirmeyi yapalım.","Eski birleşim detayından temiz yeni doğramaya match-cut; yüzey hazırlığını kısa ara planla göster."),
  content(11,"reklam-olcunu-gir","Sineklik","lead","offer","ÖLÇÜNÜ GİR. YAKLAŞIK TEKLİFİNİ AL.","ONLINE TEKLİF","Modeli, rengi ve ölçüyü seçin.","TEKLİF OLUŞTUR","social-media/source-clean/antrasit-kapi.png",12,"Sineklik için beklemeden ön teklif oluşturun. Modeli seçin, ölçünüzü girin ve seçenekleri tek ekranda görün.","Sineklik ön teklifinizi calisanyapi.com üzerinden oluşturun.","Telefon ekranı hissinde form adımları; ölçü, renk ve sonuç hızlı sırayla görünür.",{paid:true,hookVariants:["ÖLÇÜNÜ GİR. YAKLAŞIK TEKLİFİNİ AL.","SİNEKLİK FİKRİNİZİ 1 DAKİKADA NETLEŞTİRİN.","MODELİ SEÇ. ÖLÇÜYÜ YAZ. SONUCU GÖR."]}),
  content(12,"katlanir-mi-surme-mi","Cam Balkon","save","mechanism","KATLANIR MI, SÜRME Mİ? EN İYİ SİSTEM DİYE BİR ŞEY YOK.","DOĞRU EŞLEŞME","Kanatların toplanacağı alan ve kullanım alışkanlığı belirleyicidir.","KAYDET","services/cam-balkon-v2.png",28,"Katlanır sistem geniş açıklığı tamamen açabilir. Sürme sistem ise kanatların ray üzerinde hareket ettiği farklı bir kullanım sunar. Doğru seçim balkonunuza bağlıdır.","Sistem adından önce kullanım biçiminizi seçin. Karşılaştırmayı kaydedin.","İki sistemin hareket yönünü teknik oklar ve iki kolonlu editoryal düzenle karşılaştır."),
  content(13,"cam-balkon-birlesim","Cam Balkon","trust","mechanism","CAM BALKON YAPTIRMADAN ÖNCE ŞU BİRLEŞİME BAKIN.","DETAY","Zemin, tavan, profil ve su tahliyesi birlikte kontrol edilir.","KAYDET","services/lifestyle/cam-balkon-cephe-02.jpg",22,"Cam kadar profilin bağlandığı yüzey de önemlidir. Zemin ve tavan koşulları, açılım yönü ve su tahliyesi keşifte birlikte değerlendirilmelidir.","Teklifleri karşılaştırırken yalnız cam kalınlığına bakmayın. Uygulama detayını da sorun.","Alt ray, üst bağlantı ve köşe birleşimini üç ritmik makro planla göster."),
  content(14,"gorunmeyen-detay","Sineklik","trust","mechanism","İYİ UYGULAMAYI UZAKTAN GÖRÜNMEYEN DETAY BELİRLER.","İŞÇİLİK","Temiz kesim, doğru köşe, dengeli ray ve rahat hareket.","PROJEYİ İNCELE","products/beyaz-menteseli-kapi-detay.webp",20,"Ürün kapalıyken küçük görünen birleşimler, her gün kullandığınızda büyük fark yaratır. Köşeler, ray dengesi ve kapanma hissi birlikte kontrol edilir.","Yakından bakın. İşçilik kendini ayrıntıda gösterir.","Köşe birleştirme, ray ve kapanma detaylarını yüksek kontrastlı makro çekimle göster."),
  content(15,"reklam-balkon-bos-kalmasin","Cam Balkon","lead","offer","BALKONUNUZ YILIN ÇOĞUNDA BOŞ KALMASIN.","DÖRT MEVSİM","Katlanır veya sürme sistemi alanınıza göre değerlendirelim.","FOTOĞRAFLA BAŞVUR","services/lifestyle/balkon-yasam-01.jpg",15,"Yağmurda koruyun, güzel havada açın. Balkonunuzun fotoğrafını gönderin; kullanımınıza uygun cam sistemini birlikte değerlendirelim.","İstanbul’da alanınıza özel cam balkon ön değerlendirmesi. Fotoğraf ve yaklaşık ölçü yeterli.","Boş balkonla başla; camların açıldığı hareket üzerinden düzenlenmiş yaşam alanına geç.",{paid:true,hookVariants:["BALKONUNUZ YILIN ÇOĞUNDA BOŞ KALMASIN.","BU ALAN EVİNİZİN EN KEYİFLİ KÖŞESİ OLABİLİR.","YAĞMURDA KAPATIN. GÜZEL HAVADA AÇIN."]}),
  content(16,"kedi-standart-tul","Sineklik","save","problem","KEDİ OLAN EVDE STANDART TÜL SEÇMEYİN.","EVİCİL DOSTLAR","Kullanım biçimine göre güçlendirilmiş tül ve kilit seçeneği.","SEÇENEKLERİ SOR","cat-outdoor-visuals/04-dayanikli-kedi-tulu-detay.png",22,"Evcil hayvanlı bir evde yalnız böcek koruması düşünülmez. Tül dayanımı, kapanma biçimi ve güvenlik kilidi birlikte değerlendirilmelidir.","Kediniz varsa bunu ölçü talebinde mutlaka belirtin. Uygun tül ve kilit seçeneklerini konuşalım.","Pati, tül dokusu ve kilit detayını güvenli yakın planlarla göster; hayvana stres veren test yapma."),
  content(17,"genis-aciklik-tek-kanat","Sineklik","reach","mechanism","GENİŞ AÇIKLIKTA TEK KANAT NEDEN ZORLAR?","DUBLE PLİSE","İki kanat merkezde buluşur; geçişi ihtiyaca göre açarsınız.","ÖLÇÜNÜ GÖNDER","products/duble-plise-ref.webp",18,"Geniş açıklıkta tek kanadın hareket mesafesi kullanımı zorlaştırabilir. Duble plise, açıklığı iki yönden yönetmeye yardımcı olur.","Geniş kapı veya cam balkon açıklığınızı gönderin; uygun sistemi birlikte değerlendirelim.","Merkezde buluşan iki kanadı simetrik hareket ve üstten teknik çizgiyle anlat."),
  content(18,"profil-rengi","Sineklik","save","before-after","BEYAZ MI, ANTRASİT Mİ, AHŞAP TONU MU?","RENK UYUMU","Profili doğramaya değil, bütün mekâna bakarak seçin.","EKRAN GÖRÜNTÜSÜ AL","products/altinmese-menteseli-pencere.webp",18,"Profil rengi ürünü görünmez de yapabilir, tasarımın bir parçası da. Beyaz, antrasit ve ahşap tonlarını doğrama ile birlikte değerlendirin.","Hangi renk sizin evinize daha yakın? Karşılaştırmayı kaydedin.","Aynı ürün çevresinde beyaz, antrasit ve altın meşe renk swatch geçişleri."),
  content(19,"istanbul-proje-gunlugu","Cam Balkon","trust","before-after","İSTANBUL’DA BU ALAN İÇİN HANGİ ÇÖZÜMÜ KULLANDIK?","PROJE GÜNLÜĞÜ","İhtiyaç → sistem seçimi → uygulama detayı → sonuç.","BENZER ALANI GÖNDER","services/lifestyle/cam-balkon-cephe-02.jpg",30,"Her alan aynı çözümü istemez. Bu projede açıklığı, bağlantı yüzeylerini ve kullanım beklentisini inceledik; sistemi buna göre belirledik.","İlçe, sistem ve uygulama ayrıntısı gerçek proje bilgileri geldikten sonra yayına eklenecek.","Gerçek çekim geldiğinde ilçe tabelası, önce, montaj, detay ve sonuç sırasını kullan."),
  content(20,"reklam-pvc-evi-korusun","PVC","lead","offer","PENCERENİZ YALNIZ KAPANMASIN. EVİ KORUSUN.","PVC YENİLEME","Profil, cam, aksesuar ve montajı birlikte değerlendirin.","KEŞİF TALEBİ BIRAK","services/pvc-kapi-pencere-v2.webp",15,"Eski pencerenizi yenilerken yalnız profili değil, camı, açılımı ve montaj koşullarını birlikte planlayın. Fotoğrafınızı gönderin, sizi arayalım.","İstanbul PVC kapı ve pencere yenileme. Fotoğrafla ön değerlendirme talebi bırakın.","Eski pencere kolundan yeni çift açılıma match-cut; finalde form CTA.",{paid:true,hookVariants:["PENCERENİZ YALNIZ KAPANMASIN. EVİ KORUSUN.","ESKİ PENCERENİZDE SORUN PROFİL OLMAYABİLİR.","YALITIM, BEŞ DETAYIN BİRLİKTE ÇALIŞMASIDIR."]}),
  content(21,"golgeyi-yonetin","Pergola","reach","mechanism","GÜNEŞ ÇIKTIĞINDA KAÇMAYIN. GÖLGEYİ YÖNETİN.","PERGOLA","Açıklık, eğim, tahliye ve motor alanınıza göre planlanır.","ALANI DEĞERLENDİRELİM","services/pergola-v1.png",18,"Pergola yalnız gölge değildir. Açıklık, eğim, yağmur tahliyesi ve motor seçimi alanın kullanımına göre birlikte planlanır.","Teras veya bahçenizin genel fotoğrafını gönderin; ilk değerlendirmeyi yapalım.","Tavanın açılma hareketi, değişen güneş çizgisi ve su tahliye detayı."),
  content(22,"kis-bahcesi-yazin","Kış Bahçesi","save","problem","KIŞ BAHÇESİ YAZIN KULLANILAMAZ MI?","DOĞRU PLAN","Açılır cam, gölgeleme ve hava akışı birlikte düşünülür.","KAYDET","services/kis-bahcesi-v1.png",26,"Kış bahçesinin yaz konforu yalnız cam seçimine bağlı değildir. Açılır bölümler, gölgeleme ve doğal hava akışı proje aşamasında birlikte planlanmalıdır.","Dört mevsim kullanım istiyorsanız havalandırmayı en başta konuşun.","Kapalı sıcak alanla açılan cam ve gölge altındaki ferah kullanım arasında görsel karşılaştırma."),
  content(23,"manzara-ruzgar","Giyotin Cam","reach","mechanism","MANZARA AYNI. RÜZGÂR KONTROL ALTINDA.","GİYOTİN CAM","Dikey hareketle açıklığı kullanım anına göre yönetin.","SİSTEM BİLGİSİ AL","services/giyotin-cam-v1.png",16,"Motorlu giyotin cam paneller dikey hareket eder. Panel düzeni, motor, bağlantı ve güvenlik ayrıntıları alana göre projelendirilir.","Balkon, teras veya işletme açıklığınız için sistem bilgisi alın.","Cam panelin dikey hareketini takip eden kamera; manzarayı sabit tut."),
  content(24,"reklam-teras-yaz-degil","Dış Mekân","lead","offer","TERASINIZI YALNIZ YAZ İÇİN PLANLAMAYIN.","ALAN ÇÖZÜMLERİ","Pergola, cam ve kış bahçesini tek kullanım senaryosunda düşünün.","KEŞİF İSTE","services/lifestyle/balkon-yasam-01.jpg",15,"Güneş, yağmur ve rüzgâr için ayrı çözümler değil, birlikte çalışan bir alan planı oluşturun. Fotoğrafınızı gönderin, seçenekleri değerlendirelim.","Pergola, cam ve kış bahçesi çözümleri için alan fotoğrafıyla başvurun.","Güneş, yağmur ve akşam kullanımı için aynı terasın üç hızlı atmosfer geçişi.",{paid:true,hookVariants:["TERASINIZI YALNIZ YAZ İÇİN PLANLAMAYIN.","BİR TERAS. ÜÇ HAVA KOŞULU. TEK PLAN.","DIŞ MEKÂNI DÖRT MEVSİM KULLANIN."]}),
  content(25,"guvenlik-manzara","Korkuluk","trust","before-after","GÜVENLİK MANZARAYI KAPATMAK ZORUNDA DEĞİL.","KORKULUK","Cam, alüminyum veya metal; zemine ve mimariye göre.","FOTOĞRAF GÖNDER","services/lifestyle/cam-korkuluk-02.jpg",20,"Korkuluk seçimi yalnız görünüm değildir. Sabitleme zemini, kullanım yeri ve güvenlik gereksinimleri teknik olarak değerlendirilmelidir.","Balkon, teras veya merdiveninizi gönderin; uygun sistemi konuşalım.","Manzarayı izleyen geniş açıdan ankraj ve cam kenarı makrolarına geç."),
  content(26,"tavani-toparlamak","Asma Tavan","trust","before-after","TAVANI KAPATMAK BAŞKA. MEKÂNI TOPARLAMAK BAŞKA.","ASMA TAVAN","Işık, akustik ve tesisat erişimi aynı düzende.","PROJE GÖRÜŞMESİ AL","services/lifestyle/asma-tavan-01.jpg",20,"Asma tavan yalnız yüzeyi kapatmaz. Aydınlatma yerleşimi, akustik ihtiyaç ve tesisat erişimi birlikte çözüldüğünde mekân toparlanır.","Konut veya işletmeniz için tavan planını birlikte değerlendirelim.","Tesisatlı ham tavandan düzenli aydınlatmalı bitmiş mekâna yukarı yönlü wipe."),
  content(27,"kupeste-baglanti","Küpeşte","trust","mechanism","SAĞLAM KÜPEŞTEYİ BAĞLANTI DETAYINDAN TANIRSINIZ.","İŞÇİLİK","Eğim, dönüş, tutuş ve sabitleme birlikte çözülür.","DETAYI KAYDET","services/lifestyle/kupeste-02.jpg",18,"Küpeşte hattında temiz görünüm kadar dönüşler ve bağlantı noktaları önemlidir. Malzeme seçimi iç veya dış mekâna göre yapılır.","Merdiveninizin genel görünümünü gönderin; ilk değerlendirmeyi yapalım.","Tutamak boyunca kayan kamera, köşe dönüşü ve bağlantı vidasında durur."),
  content(28,"reklam-alani-goster","Tüm Hizmetler","lead","offer","ALANI GÖSTERİN. DOĞRU SİSTEMİ BİRLİKTE SEÇELİM.","FOTOĞRAFLA ÖN DEĞERLENDİRME","Hizmet, ilçe, yaklaşık ölçü ve alan fotoğrafı yeterli.","FOTOĞRAFLA BAŞVUR","brand/calisan-yapi-hero.png",15,"Sineklikten cam balkona, PVC’den pergolaya kadar alanınıza uygun çözümü birlikte değerlendirelim. Fotoğraf ve yaklaşık ölçüyü gönderin.","İstanbul genelinde fotoğrafla ön değerlendirme. Alanınızı gösterin, sizi arayalım.","Dört hizmetten hızlı detaylar; finalde fotoğraf yükleme alanı ve tek CTA.",{paid:true,hookVariants:["ALANI GÖSTERİN. DOĞRU SİSTEMİ BİRLİKTE SEÇELİM.","HANGİ SİSTEM OLDUĞUNU BİLMENİZ GEREKMİYOR.","BİR FOTOĞRAF, İLK DEĞERLENDİRME İÇİN YETERLİ."]}),
  content(29,"montajdan-once","Marka","trust","mechanism","BİR UYGULAMA MONTAJDAN ÖNCE NASIL HAZIRLANIYOR?","PERDE ARKASI","Ölçü, malzeme, kesim, kontrol ve saha hazırlığı.","TAKİP ET","products/beyaz-menteseli-kapi-detay.webp",28,"Sahadaki temiz sonuç, montajdan önce başlar. Ölçüler, renk, mekanizma ve parçalar kontrol edilir; uygulama sırası buna göre hazırlanır.","Gerçek üretim ve montaj süreçlerini görmek için takip edin.","Yüz göstermeden el, ölçü, kesim, parça kontrolü ve paketleme ritmi."),
  content(30,"en-cok-sorulanlar","Tüm Hizmetler","lead","problem","30 GÜNDE EN ÇOK SORULAN 5 SORU.","HIZLI CEVAP","Model, ölçü, fotoğraf, keşif ve teklif süreci.","SORUNU YORUMA YAZ","brand/calisan-yapi-hero.png",35,"Hangi model uygun? Yaklaşık ölçü yeterli mi? Fotoğrafla değerlendirme yapılır mı? Kesin fiyat ne zaman çıkar? İstanbul’un hangi ilçelerine geliyorsunuz? Hepsini kısa kısa yanıtlıyoruz.","Cevabını bulamadığınız soruyu yorumlara yazın; sonraki videoda ele alalım.","Her soruyu numaralı büyük tipografi ve ilgili ürün detayının kısa kesitiyle eşleştir."),
];

export const getContent = (day: number) => socialContent.find((item) => item.day === day);

export const buildProductionPrompt = (item: SocialContent) => ({
  visual: `Sağlanan özgün Çalışan Yapı görüntüsünü temel al. ${item.visualDirection} Ürünün geometrisini, profil rengini, ray, tül veya cam detayını ve gerçek montaj koşullarını değiştirme. Doğal ışığı ve malzeme okunurluğunu iyileştir. Metin, logo, filigran veya hayalî yapı elemanı ekleme. 9:16 dikey çıktı üret.`,
  motion: `İlk 0–2 saniyede “${item.hook}” mesajını görünür ürün veya el hareketiyle ver. ${item.visualDirection} Kanıt: ${item.proof} Son karede yalnız “${item.cta}” CTA'sını göster. Ürünün gerçek çalışma biçimini değiştirecek yapay hareket üretme.`,
  voiceover: item.voiceover,
  caption: item.caption,
});
