import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowUpRight } from "lucide-react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { JsonLd } from "@/components/JsonLd";
import { ContentTracker } from "@/components/ContentTracker";
import { LocalServiceShowcase } from "@/components/LocalServiceShowcase";
import { getDistrictNeighborhoods } from "@/lib/content";
import { districts, getDistrict, site } from "@/lib/site";
type Props = { params: Promise<{ ilce: string }> };
export function generateStaticParams() { return districts.map(({ slug }) => ({ ilce: slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const district = getDistrict((await params).ilce); if (!district) return {}; return { title: `${district.name} PVC Pencere ve Yapı Hizmetleri`, description: `${district.name} bölgesinde PVC pencere, cam balkon, sineklik ve yapı sistemleri için yerinde keşif, ölçü ve uygulama seçeneklerini inceleyin.`, alternates: { canonical: `/istanbul/${district.slug}` }, robots: { index: false, follow: true } }; }
export default async function DistrictPage({ params }: Props) { const district = getDistrict((await params).ilce); if (!district) notFound(); const districtUrl = `${site.url}/istanbul/${district.slug}`; const localNeighborhoods = getDistrictNeighborhoods(district.slug); return <><ContentTracker type="district" slug={district.slug} district={district.slug}/><JsonLd data={{ "@context":"https://schema.org", "@graph":[{ "@type":"CollectionPage", "@id":`${districtUrl}#webpage`, url:districtUrl, name:`${district.name} Yapı Hizmetleri`, spatialCoverage:{"@type":"AdministrativeArea",name:district.name}, publisher:{"@id":`${site.url}/#organization`} }, { "@type":"BreadcrumbList", itemListElement:[{ "@type":"ListItem", position:1, name:"Ana Sayfa", item:site.url }, { "@type":"ListItem", position:2, name:"İstanbul Hizmet Bölgeleri", item:`${site.url}/istanbul` }, { "@type":"ListItem", position:3, name:district.name, item:districtUrl }] }] }}/><SiteHeader/><main className="inner-page"><section className="service-hero technical-paper"><div><p className="kicker">İstanbul · {district.name}</p><h1 className="font-display">{district.name} yapı<br/><em>uygulamaları.</em></h1></div><div><p>{district.name} genelinde PVC kapı-pencere, cam balkon, küpeşte, korkuluk, asma tavan, sineklik, kış bahçesi, pergola ve giyotin cam ihtiyaçları için yerinde ölçü ve planlı uygulama desteği sunuyoruz.</p><Link href={`/teklif-al?ilce=${district.slug}&from=${encodeURIComponent(`/istanbul/${district.slug}`)}`} className="btn-primary">{district.name} için keşif iste <ArrowUpRight size={17}/></Link></div></section><LocalServiceShowcase placeName={district.name}/>{localNeighborhoods.length>0&&<section className="neighborhood-index"><header><p className="kicker">Semtler</p><h2 className="font-display">{district.name} içinde<br/><em>hizmet noktaları.</em></h2></header><div>{localNeighborhoods.map((item,index)=><Link href={`/istanbul/${district.slug}/${item.slug}`} key={item.slug}><span>{String(index+1).padStart(2,"0")}</span><b>{item.name}</b><ArrowUpRight size={16}/></Link>)}</div></section>}</main><SiteFooter/></> }
