"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import Image from "next/image";
import { ArrowLeft, ArrowRight, Check, CircleHelp, ImagePlus, Minus, PackageCheck, Plus, Ruler, Truck, Wrench, X } from "lucide-react";
import { calculateQuote, formatMoney } from "@/lib/pricing";
import { productImage } from "@/lib/product-images";
import type { Catalog, CustomerInput, Fulfilment, QuoteItemInput, QuotePricing } from "@/lib/types";

const DRAFT_KEY = "cy_quote_draft_v8";
const makeItem = (): QuoteItemInput => ({ id: crypto.randomUUID(), openingType: "window", label: "Pencere", productSlug: "sabit-citcitli", width: 0, height: 0, quantity: 1, colorSlug: "beyaz", featureSlugs: [] });
type Draft = { items: QuoteItemInput[]; fulfilment: Fulfilment; customer: CustomerInput; kvkk: boolean };
const initialDraft = (): Draft => ({ items: [makeItem()], fulfilment: { type: "shipping", city: "", district: "", address: "" }, customer: { name: "", phone: "", email: "", notes: "" }, kvkk: false });
const steps = ["Ürün ve ölçü", "Teslimat", "İletişim"];

export function QuoteBuilder({ catalog }: { catalog: Catalog }) {
  const [step, setStep] = useState(0);
  const [draft, setDraft] = useState<Draft>(initialDraft);
  const [hydrated, setHydrated] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState<{ reference: string; pricing: QuotePricing } | null>(null);

  useEffect(() => {
    queueMicrotask(() => {
      try { const saved = localStorage.getItem(DRAFT_KEY); if (saved) setDraft(JSON.parse(saved)); } catch {}
      setHydrated(true);
    });
  }, []);
  useEffect(() => { if (hydrated) localStorage.setItem(DRAFT_KEY, JSON.stringify(draft)); }, [draft, hydrated]);

  const pricing = useMemo(() => { if (draft.items.some(item => item.width <= 0 || item.height <= 0)) return null; try { return calculateQuote(draft.items, draft.fulfilment.type, catalog); } catch { return null; } }, [draft.items, draft.fulfilment.type, catalog]);
  const updateItem = (id: string, patch: Partial<QuoteItemInput>) => setDraft((current) => ({ ...current, items: current.items.map((item) => item.id === id ? { ...item, ...patch } : item) }));
  const setFulfilment = (type: "shipping" | "installation") => setDraft((d) => ({ ...d, fulfilment: type === "installation" ? { type, city: "İstanbul", district: "", address: "" } : { type, city: "", district: "", address: "" } }));

  const validateStep = () => {
    setError("");
    if (step === 0) {
      try { calculateQuote(draft.items, draft.fulfilment.type, catalog); } catch (cause) { setError(cause instanceof Error ? cause.message : "Ölçüleri kontrol edin."); return false; }
    }
    if (step === 1 && (!draft.fulfilment.city.trim() || draft.fulfilment.district.trim().length < 2 || draft.fulfilment.address.trim().length < 8)) { setError("Teslimat veya montaj adresini eksiksiz girin."); return false; }
    if (step === 2 && (draft.customer.name.trim().length < 2 || !/^(\+90|0)?\s?5\d{2}\s?\d{3}\s?\d{2}\s?\d{2}$/.test(draft.customer.phone.trim()) || !draft.kvkk)) { setError("Ad, geçerli telefon ve KVKK onayı zorunludur."); return false; }
    return true;
  };
  const next = () => { if (validateStep()) setStep((value) => Math.min(2, value + 1)); };
  const submit = async () => {
    if (!validateStep() || !pricing) return;
    setBusy(true); setError("");
    try {
      const response = await fetch("/api/quotes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: draft.items, fulfilment: draft.fulfilment, customer: draft.customer, kvkkAccepted: draft.kvkk, website: "" }) });
      const json = await response.json();
      if (!response.ok) throw new Error(json.error || "Teklif kaydedilemedi.");
      setSuccess({ reference: json.reference, pricing: json.pricing }); localStorage.removeItem(DRAFT_KEY);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Bağlantı hatası."); } finally { setBusy(false); }
  };

  if (success) return <Success reference={success.reference} pricing={success.pricing} onReset={() => { setDraft(initialDraft()); setSuccess(null); setStep(0); }} />;

  return (
    <section id="teklif" className="technical-paper min-h-screen overflow-x-clip scroll-mt-0 px-4 pb-28 pt-14 md:px-8 md:py-24">
      <div className="mx-auto max-w-[1480px]">
        <div className="mb-12 grid gap-8 border-b border-[var(--line)] pb-10 md:grid-cols-[1fr_auto] md:items-end">
          <div><p className="mb-3 text-[10px] font-bold uppercase tracking-[.25em] text-[var(--teal-dark)]">Çalışan Yapı · Teklif oluşturucu</p><h2 className="font-display max-w-5xl text-[clamp(3.2rem,7vw,7rem)] leading-[.8] tracking-[-.04em]">Sinekliğinizi<br/><i className="font-normal text-[var(--teal-dark)]">ölçünüze göre oluşturun.</i></h2></div>
          <div className="max-w-xs border-l border-[var(--line)] pl-5 text-sm leading-6 text-[var(--ink-soft)]"><Ruler className="mb-4 text-[var(--teal-dark)]" size={22}/><p>Uygulama yerini seçin, iki ölçüyü girin ve fiyatı anında görün.</p></div>
        </div>

        <nav aria-label="Teklif adımları" className="mb-8 grid grid-cols-3 border border-[var(--line)] bg-[rgba(243,240,232,.8)]">
          {steps.map((label, index) => <button key={label} onClick={() => index <= step && setStep(index)} className={`relative px-2 py-4 text-[9px] font-bold uppercase tracking-[.12em] md:text-[11px] ${index === step ? "bg-[var(--ink)] text-white" : index < step ? "text-[var(--teal-dark)]" : "text-[var(--ink-soft)]"}`}><span className="mr-1 opacity-50">0{index + 1}</span> {label}</button>)}
        </nav>

        <div className="grid gap-7 xl:grid-cols-[minmax(0,1fr)_370px]">
          <div className="min-h-[650px] border border-[var(--line)] bg-[rgba(255,255,255,.48)] p-4 shadow-[0_30px_80px_rgba(23,35,38,.08)] md:p-8">
            <AnimatePresence mode="wait"><motion.div key={step} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .25 }}>
              {step === 0 && <Measurements catalog={catalog} item={draft.items[0]} updateItem={updateItem} />}
              {step === 1 && <Delivery fulfilment={draft.fulfilment} setType={setFulfilment} update={(patch) => setDraft((d) => ({ ...d, fulfilment: { ...d.fulfilment, ...patch } as Fulfilment }))} catalog={catalog} />}
              {step === 2 && <Contact draft={draft} setDraft={setDraft} pricing={pricing} />}
            </motion.div></AnimatePresence>
            {error && <p role="alert" className="mt-6 border-l-2 border-red-700 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p>}
            <div className="mt-9 flex items-center justify-between border-t border-[var(--line)] pt-6">
              <button className="btn-ghost" disabled={step === 0} onClick={() => setStep((value) => Math.max(0, value - 1))}><ArrowLeft size={14}/> Geri</button>
              {step < 2 ? <button className="btn-primary" onClick={next}>Devam et <ArrowRight size={14}/></button> : <button className="btn-primary" disabled={busy} onClick={submit}>{busy ? "Kaydediliyor…" : "Teklifi kaydet"} <Check size={15}/></button>}
            </div>
          </div>
          <div className="hidden xl:block"><PricePanel pricing={pricing} fulfilment={draft.fulfilment.type} settings={catalog.settings} /></div>
        </div>
      </div>
      <MobilePriceBar pricing={pricing}/>
    </section>
  );
}

function SectionTitle({ number, title, text }: { number: string; title: string; text: string }) { return <header className="mb-8"><span className="text-[10px] font-bold uppercase tracking-[.2em] text-[var(--teal-dark)]">{number}</span><h3 className="font-display mt-2 text-5xl leading-none md:text-6xl">{title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--ink-soft)]">{text}</p></header>; }

function Measurements({ catalog, item, updateItem }: { catalog: Catalog; item: QuoteItemInput; updateItem:(id:string,p:Partial<QuoteItemInput>)=>void }) {
  return <><SectionTitle number="01 / Ürün ve ölçü" title="Nereye uygulayacağız?" text="Kullanım yerini seçin, iç fitilden iç fitile ölçüyü girin. Görsel ve fiyat siz girdikçe oluşur."/><ItemEditor item={item} catalog={catalog} updateItem={updateItem}/></>;
}

function ItemEditor({item,catalog,updateItem}:{item:QuoteItemInput;catalog:Catalog;updateItem:(id:string,p:Partial<QuoteItemInput>)=>void}) {
  const [guideOpen,setGuideOpen]=useState(false);
  const product=catalog.products.find((p)=>p.slug===item.productSlug)!;
  const upload=async(file?:File)=>{if(!file)return;const form=new FormData();form.append("file",file);const res=await fetch("/api/uploads",{method:"POST",body:form});const json=await res.json();if(res.ok)updateItem(item.id,{photoPath:json.path});else alert(json.error||"Fotoğraf yüklenemedi.");};
  const openingOptions = [
    { type:"window" as const, label:"Pencere", slug:"sabit-citcitli", note:"Standart ve geniş pencereler" },
    { type:"door" as const, label:"Kapı", slug:"surme", note:"Balkon ve teras kapıları" },
    { type:"glass-balcony" as const, label:"Geniş açıklık", slug:"duble", note:"Cam balkon ve geniş geçişler" },
  ];
  const chooseOpening=(option:(typeof openingOptions)[number])=>updateItem(item.id,{openingType:option.type,label:option.label,productSlug:option.slug,width:0,height:0});
  const solutionCopy: Record<string,{label:string,note:string,fit:string}> = {
    "sabit-citcitli": {label:"Sabit",note:"Açıp kapatmanız gerekmeyen alanlar için yalın çözüm.",fit:"Pencere ve küçük açıklıklar"},
    surme: {label:"Sürgülü",note:"Günlük kullanımda ray üzerinde rahatça yana açılır.",fit:"Kapı ve sürgülü doğramalar"},
    duble: {label:"Duble sürgülü",note:"İki kanat ortada buluşur; geniş geçişi dengeli kapatır.",fit:"Geniş balkon ve cam balkonlar"},
  };
  const systemOptions = ["sabit-citcitli","surme","duble"].map(slug=>{const product=catalog.products.find(candidate=>candidate.slug===slug);return product&&product.active?{slug,...solutionCopy[slug]}:null}).filter((option): option is {slug:string;label:string;note:string;fit:string}=>Boolean(option));
  const chooseSystem=(slug:string)=>updateItem(item.id,{productSlug:slug,width:0,height:0});
  return <div className="border border-[var(--line)] bg-white/55 p-4 md:p-6">
    <div className="grid gap-2 sm:grid-cols-3">{openingOptions.map(option=><button key={option.type} onClick={()=>chooseOpening(option)} className={`group min-h-28 min-w-0 border p-3 text-left transition md:min-h-36 md:p-4 ${item.openingType===option.type?"border-[var(--ink)] bg-[var(--ink)] text-white":"border-[var(--line)] bg-[var(--paper-deep)] hover:border-[var(--teal-dark)]"}`}><OpeningIcon type={option.type}/><strong className="font-display mt-2 block text-2xl md:mt-3 md:text-3xl">{option.label}</strong><span className={`mt-1 block text-[8px] leading-3 md:text-[10px] ${item.openingType===option.type?"text-white/50":"text-[var(--ink-soft)]"}`}>{option.note}</span></button>)}</div>

    <div className="mt-5 border-t border-[var(--line)] pt-5"><span className="text-[10px] font-bold uppercase tracking-[.2em] text-[var(--teal-dark)]">Size uygun çözümü seçin</span><p className="mt-2 max-w-xl text-xs leading-5 text-[var(--ink-soft)]">Üç net seçenek. Ölçünüzü girin; seçimin uygunluğunu ekibimiz teklif öncesinde kontrol etsin.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{systemOptions.map((option,index)=><button key={option.slug} onClick={()=>chooseSystem(option.slug)} className={`group relative min-w-0 overflow-hidden border text-left transition duration-200 ${item.productSlug===option.slug?"border-[var(--teal-dark)] bg-[#edf7f4] shadow-[0_12px_30px_rgba(8,117,111,.12)]":"border-[var(--line)] bg-white/55 hover:-translate-y-0.5 hover:border-[var(--teal-dark)]"}`}><span className="relative block aspect-[5/3] bg-[#ded8cc]"><Image src={productImage(option.slug)} alt={`${option.label} sineklik çözümü`} fill sizes="(max-width:700px) 100vw, 260px" className="object-cover transition duration-500 group-hover:scale-[1.03]"/><span className="absolute left-3 top-3 bg-[var(--ink)] px-2 py-1 text-[8px] font-bold tracking-[.15em] text-white/65">0{index+1}</span></span><span className="block min-h-40 p-4"><span className="flex items-start justify-between gap-3"><strong className="font-display block text-3xl leading-none">{option.label}</strong>{item.productSlug===option.slug&&<span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[var(--teal-dark)] text-white"><Check size={15}/></span>}</span><small className="mt-3 block text-[10px] leading-4 text-[var(--ink-soft)]">{option.note}</small><b className="mt-4 block border-t border-[var(--line)] pt-3 text-[9px] uppercase tracking-[.1em] text-[var(--teal-dark)]">{option.fit}</b></span></button>)}</div><div className="mt-3 flex items-center justify-between gap-4 border-l-4 border-[var(--teal-dark)] bg-[var(--paper-deep)] px-4 py-3"><p className="text-[10px] leading-4 text-[var(--ink-soft)]"><strong className="text-[var(--ink)]">Kararsız mısınız?</strong> Yaklaşık ölçüyü girin; doğru çözümü birlikte netleştirelim.</p><span className="shrink-0 text-[9px] font-bold uppercase tracking-[.12em] text-[var(--teal-dark)]">Ölçüye geç ↓</span></div></div>

    <MobileLivePreview item={item} catalog={catalog}/>

    <div className="mt-7 grid overflow-hidden border border-[var(--line)] bg-[#ebe6dc] lg:grid-cols-[minmax(0,1.45fr)_380px]">
      <div className="hidden lg:block"><CombinedVisual item={item} catalog={catalog}/></div>
      <div className="border-t border-[var(--line)] bg-[var(--paper)] p-5 lg:border-l lg:border-t-0 md:p-7">
        <div className="flex items-center justify-between gap-3"><span className="text-[9px] font-bold uppercase tracking-[.18em] text-[var(--teal-dark)]">2 · İç fitil ölçüsü</span><button type="button" onClick={()=>setGuideOpen(true)} className="inline-flex items-center gap-1.5 text-[10px] font-bold text-[var(--teal-dark)]"><CircleHelp size={17}/> Nasıl ölçülür?</button></div>
        <div className="mt-5 space-y-4"><NumberControl label="Genişlik" value={item.width} min={product.minWidth} max={product.maxWidth} unit="cm" onChange={value=>updateItem(item.id,{width:value})}/><NumberControl label="Yükseklik" value={item.height} min={product.minHeight} max={product.maxHeight} unit="cm" onChange={value=>updateItem(item.id,{height:value})}/><NumberControl label="Adet" value={item.quantity} min={1} max={50} unit="adet" onChange={value=>updateItem(item.id,{quantity:value})}/></div>
        <div className="mt-6"><span className="label">Profil rengi</span><p className="mb-3 text-[9px] leading-4 text-[var(--ink-soft)]">En çok tercih edilen üç renk.</p><div className="grid grid-cols-3 gap-2">{catalog.colors.filter(c=>c.active&&["beyaz","antrasit","ahsap"].includes(c.slug)).map(color=><button key={color.slug} title={color.name} aria-label={color.name} onClick={()=>updateItem(item.id,{colorSlug:color.slug})} className={`relative flex items-center gap-2 border p-2 text-left transition ${item.colorSlug===color.slug?"border-[var(--teal-dark)] bg-[#edf7f4]":"border-[var(--line)] bg-white/45"}`}><span className="h-8 w-8 shrink-0 border border-black/10" style={{background:color.hex}}/>{item.colorSlug===color.slug&&<Check className="absolute right-1 top-1 text-[var(--teal-dark)]" size={12}/>}<small className="truncate text-[8px] font-bold">{color.name}</small></button>)}</div></div>
        <AnimatePresence>{guideOpen&&<motion.div className="fixed inset-0 z-[80] grid place-items-center bg-black/65 p-4 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setGuideOpen(false)}><motion.div role="dialog" aria-modal="true" aria-labelledby="measure-guide-title" initial={{opacity:0,y:24,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:16}} onClick={event=>event.stopPropagation()} className="w-full max-w-xl border border-white/15 bg-[var(--paper)] p-5 shadow-2xl md:p-8"><div className="flex items-start justify-between gap-4"><div><span className="text-[9px] font-bold uppercase tracking-[.18em] text-[var(--teal-dark)]">Ölçü referansı</span><h4 id="measure-guide-title" className="font-display mt-1 text-4xl">İç fitilden iç fitile</h4></div><button type="button" aria-label="Kılavuzu kapat" onClick={()=>setGuideOpen(false)} className="border border-[var(--line)] p-2"><X size={18}/></button></div><MeasureGuide/><button type="button" className="btn-primary mt-4 w-full" onClick={()=>setGuideOpen(false)}>Anladım, ölçüye dön</button></motion.div></motion.div>}</AnimatePresence>
        <label className="mt-4 flex cursor-pointer items-center gap-3 border border-dashed border-[var(--line)] bg-white/35 p-3 text-[10px] text-[var(--ink-soft)]"><ImagePlus size={16}/><span>{item.photoPath?"Fotoğraf eklendi":"İsterseniz fotoğraf ekleyin"}</span><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></label>
      </div>
    </div>
    {catalog.features.filter(feature=>feature.active&&feature.slug==="pet").map(feature=>{const selected=item.featureSlugs.includes("pet");return <div className="mt-5" key={feature.slug}><span className="label">Güçlendirilmiş tül · isteğe bağlı</span><button type="button" onClick={()=>updateItem(item.id,{featureSlugs:selected?[]:["pet"]})} className={`mt-2 flex w-full items-center justify-between gap-5 border p-4 text-left transition ${selected?"border-[var(--teal-dark)] bg-[#edf7f4] shadow-[0_10px_24px_rgba(8,117,111,.10)]":"border-[var(--line)] bg-white/40 hover:border-[var(--teal-dark)]"}`}><span className="flex items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${selected?"bg-[var(--teal-dark)] text-white":"border border-[var(--line)] text-[var(--teal-dark)]"}`}>{selected?<Check size={17}/>:<Plus size={17}/>}</span><span><strong className="block text-sm">Kedi tülü / Güçlendirilmiş tül</strong><small className="mt-1 block text-[9px] leading-4 text-[var(--ink-soft)]">Evcil hayvan bulunan alanlar için daha dayanıklı tül seçeneği.</small></span></span><b className="shrink-0 text-xs text-[var(--teal-dark)]">+{formatMoney(feature.price)}</b></button></div>})}
  </div>;
}

function MobileLivePreview({item,catalog}:{item:QuoteItemInput;catalog:Catalog}) { const product=catalog.products.find(p=>p.slug===item.productSlug);const color=catalog.colors.find(c=>c.slug===item.colorSlug);const ratio=Math.max(.55,Math.min(1.45,(item.width||100)/(item.height||100)));return <div className="sticky top-0 z-30 mt-4 w-full max-w-full overflow-hidden border border-white/10 bg-[var(--ink)] p-2.5 text-white shadow-[0_12px_30px_rgba(23,35,38,.25)] lg:hidden"><div className="grid grid-cols-[minmax(0,1fr)_92px] gap-2"><div className="relative h-28 min-w-0 overflow-hidden bg-[#ded8cc]"><AnimatePresence mode="wait"><motion.div key={`${item.productSlug}-${item.colorSlug}`} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="absolute inset-0 p-2"><div className="relative h-full"><Image src={productImage(item.productSlug,item.colorSlug)} alt={`${product?.name ?? "Sineklik"} mobil önizleme`} fill sizes="65vw" className="object-contain"/></div></motion.div></AnimatePresence><span className="absolute bottom-1.5 left-2 max-w-[85%] truncate bg-black/65 px-2 py-1 text-[7px] uppercase tracking-[.1em]">{product?.name}</span></div><div className="relative grid h-28 place-items-center overflow-hidden bg-[#10191b]"><motion.div layout className="relative border-4 bg-[repeating-linear-gradient(90deg,rgba(120,213,207,.12)_0_2px,transparent_2px_7px)]" style={{borderColor:color?.hex,width:`${Math.min(58,44*ratio)}px`,height:`${Math.min(72,58/ratio)}px`}}/><span className="absolute bottom-1.5 whitespace-nowrap text-[7px] text-[#78d5cf]">{item.width||0} × {item.height||0} cm</span></div></div><div className="mt-1.5 flex min-w-0 items-center justify-between gap-2"><span className="text-[7px] uppercase tracking-[.12em] text-white/45">Canlı önizleme</span><strong className="truncate text-[9px]">{item.label} · {color?.name}</strong></div></div>}

function CombinedVisual({item,catalog}:{item:QuoteItemInput;catalog:Catalog}) { const product=catalog.products.find(p=>p.slug===item.productSlug);const color=catalog.colors.find(c=>c.slug===item.colorSlug);return <div className="grid min-h-[560px] bg-[#ded8cc] md:grid-cols-[1.25fr_.75fr]"><div className="relative min-h-[360px] border-b border-[var(--line)] md:border-b-0 md:border-r"><AnimatePresence mode="wait"><motion.div key={`${item.productSlug}-${item.colorSlug}`} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="absolute inset-0 p-6"><div className="relative h-full w-full"><Image src={productImage(item.productSlug,item.colorSlug)} alt={`${product?.name ?? "Sineklik"} tam görünümü`} fill sizes="(max-width:1024px) 100vw,600px" className="object-contain" priority/></div></motion.div></AnimatePresence><span className="absolute left-4 top-4 bg-[var(--ink)] px-3 py-2 text-[9px] font-bold uppercase tracking-[.14em] text-[#78d5cf]">Ürün görünümü</span></div><GeometricPreview item={item} color={color?.hex ?? "#ece9df"}/></div>}

function GeometricPreview({item,color}:{item:QuoteItemInput;color:string}) { const width=item.width||100;const height=item.height||100;const ratio=Math.max(.45,Math.min(1.6,width/height));return <div className="relative grid min-h-[300px] place-items-center overflow-hidden bg-[#172326] p-8 text-white"><span className="absolute left-4 top-4 text-[9px] font-bold uppercase tracking-[.14em] text-[#78d5cf]">Canlı ölçü çizimi</span><div className="relative flex max-h-[310px] max-w-[220px] items-center justify-center" style={{width:`${Math.min(210,150*ratio)}px`,height:`${Math.min(300,210/ratio)}px`}}><motion.div layout className="relative h-full w-full border-[8px] bg-[repeating-linear-gradient(90deg,rgba(120,213,207,.10)_0_2px,transparent_2px_9px)]" style={{borderColor:color}}><div className="absolute inset-2 border border-white/20"/></motion.div><div className="absolute -bottom-7 inset-x-0 flex items-center gap-2 text-[9px]"><i className="h-px flex-1 bg-[#78d5cf]"/><b>{item.width>0?`${item.width} cm`:"— cm"}</b><i className="h-px flex-1 bg-[#78d5cf]"/></div><div className="absolute -right-16 top-0 flex h-full items-center gap-2 text-[9px]" style={{writingMode:"vertical-rl"}}><i className="w-px flex-1 bg-[#78d5cf]"/><b>{item.height>0?`${item.height} cm`:"— cm"}</b><i className="w-px flex-1 bg-[#78d5cf]"/></div></div><p className="absolute bottom-4 inset-x-4 text-center text-[9px] leading-4 text-white/40">Oran, girdiğiniz en ve boya göre değişir.</p></div>}

function OpeningIcon({type}:{type:QuoteItemInput["openingType"]}) { const common={fill:"none",stroke:"currentColor",strokeWidth:1.4,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};return <svg viewBox="0 0 64 52" className="h-12 w-16 text-[var(--teal)]" aria-hidden>{type==="window"&&<><rect x="11" y="5" width="42" height="40" {...common}/><path d="M32 5v40M11 25h42M16 20l11-10M37 40l11-10" {...common}/></>}{type==="door"&&<><path d="M16 47V4h32v43M22 47V10h20v37" {...common}/><circle cx="38" cy="29" r="1.5" fill="currentColor"/></>}{type==="glass-balcony"&&<><path d="M5 46h54M8 7h48v39M20 7v39M32 7v39M44 7v39" {...common}/><path d="M10 26h8m4 0h8m4 0h8m4 0h8" {...common}/></>}{type==="other"&&<><circle cx="32" cy="26" r="20" {...common}/><path d="M32 15v14m0 8v.5" {...common}/></>}</svg>}

function MeasureGuide() { return <div className="border-t border-[var(--line)] p-4"><svg viewBox="0 0 320 150" className="w-full" aria-label="İç fitilden iç fitile ölçüm şeması"><rect x="32" y="20" width="256" height="108" rx="2" fill="#d8d1c4" stroke="#172326" strokeWidth="8"/><rect x="55" y="39" width="210" height="70" fill="#eef6f4" stroke="#18a79f" strokeWidth="3"/><path d="M55 30v90M265 30v90M48 74h224" stroke="#08756f" strokeWidth="1.5" strokeDasharray="4 4"/><path d="m48 74 10-5v10zm224 0-10-5v10z" fill="#08756f"/><text x="160" y="68" textAnchor="middle" fontSize="11" fill="#172326">İÇ FİTİLDEN İÇ FİTİLE</text><text x="160" y="143" textAnchor="middle" fontSize="9" fill="#4f6263">Metreyi lastik fitillerin iç kenarına dayayın</text></svg><ol className="mt-2 space-y-1 text-[10px] leading-4 text-[var(--ink-soft)]"><li>1. Genişliği üst, orta ve alttan ölçün.</li><li>2. Yüksekliği sağ, orta ve soldan ölçün.</li><li>3. Her iki yönde de en küçük değeri girin.</li></ol></div>}

function NumberControl({label,value,min,max,unit,onChange}:{label:string;value:number;min:number;max:number;unit:string;onChange:(value:number)=>void}) { const step=(next:number)=>onChange(Math.min(max,Math.max(min,Math.round(next))));return <div><div className="mb-2 flex justify-between"><span className="label mb-0">{label}</span><span className="text-[9px] text-[var(--ink-soft)]">{min}–{max} {unit}</span></div><div className="grid grid-cols-[48px_1fr_48px] border border-[var(--line)] bg-white"><button type="button" aria-label={`${label} azalt`} onClick={()=>step(value>0?value-1:min)} className="grid place-items-center border-r border-[var(--line)] hover:bg-[var(--paper-deep)]"><Minus size={15}/></button><label className="relative"><input className="h-16 w-full bg-transparent px-4 text-center font-display text-4xl outline-none" type="number" inputMode="numeric" min={min} max={max} value={value||""} placeholder="0" onChange={e=>onChange(Number(e.target.value))}/><span className="absolute bottom-1 right-2 text-[8px] font-bold uppercase tracking-[.1em] text-[var(--ink-soft)]">{unit}</span></label><button type="button" aria-label={`${label} artır`} onClick={()=>step(value>0?value+1:min)} className="grid place-items-center border-l border-[var(--line)] hover:bg-[var(--paper-deep)]"><Plus size={15}/></button></div></div>}

function Delivery({fulfilment,setType,update,catalog}:{fulfilment:Fulfilment;setType:(t:"shipping"|"installation")=>void;update:(p:Partial<Fulfilment>)=>void;catalog:Catalog}) { return <><SectionTitle number="02 / Teslim şekli" title="Kapınıza mı, kasanıza mı?" text="Türkiye&apos;nin her yerine ürün gönderiyoruz. İstanbul&apos;da dilerseniz ölçü doğrulama ve montaj hizmetini ekleyin."/><div className="grid gap-3 md:grid-cols-2"><Choice active={fulfilment.type==="shipping"} onClick={()=>setType("shipping")} icon={<Truck/>} title="Kargo ile teslim" text={`Kargo ${formatMoney(catalog.settings.shippingFee)} · ${formatMoney(catalog.settings.freeShippingThreshold)} üzeri ücretsiz`}/><Choice active={fulfilment.type==="installation"} onClick={()=>setType("installation")} icon={<Wrench/>} title="İstanbul&apos;da montaj" text={`Ölçü doğrulama ve montaj ${formatMoney(catalog.settings.installationFee)}`}/></div><div className="mt-8 grid gap-5 md:grid-cols-2"><Field label="İl"><input className="field" value={fulfilment.city} readOnly={fulfilment.type==="installation"} placeholder="İstanbul" onChange={e=>update({city:e.target.value})}/></Field><Field label="İlçe"><input className="field" value={fulfilment.district} onChange={e=>update({district:e.target.value})}/></Field><div className="md:col-span-2"><Field label="Açık adres"><textarea className="field min-h-28 resize-y" value={fulfilment.address} onChange={e=>update({address:e.target.value})} placeholder="Mahalle, cadde/sokak, bina ve daire numarası"/></Field></div></div></>; }

function Contact({draft,setDraft,pricing}:{draft:Draft;setDraft:React.Dispatch<React.SetStateAction<Draft>>;pricing:QuotePricing|null}) { const setCustomer=(p:Partial<CustomerInput>)=>setDraft(d=>({...d,customer:{...d.customer,...p}})); return <><SectionTitle number="03 / Son kontrol" title="Size ulaşalım." text="Teklifiniz kaydedildikten sonra ekibimiz ölçü ve ürün uygunluğu için sizinle iletişime geçer."/><div className="grid gap-5 md:grid-cols-2"><Field label="Ad soyad"><input className="field" autoComplete="name" value={draft.customer.name} onChange={e=>setCustomer({name:e.target.value})}/></Field><Field label="Cep telefonu"><input className="field" type="tel" autoComplete="tel" placeholder="0532 000 00 00" value={draft.customer.phone} onChange={e=>setCustomer({phone:e.target.value})}/></Field><Field label="E-posta · isteğe bağlı"><input className="field" type="email" autoComplete="email" value={draft.customer.email} onChange={e=>setCustomer({email:e.target.value})}/></Field><Field label="Not · isteğe bağlı"><input className="field" value={draft.customer.notes} onChange={e=>setCustomer({notes:e.target.value})}/></Field></div><label className="mt-7 flex cursor-pointer items-start gap-3 border border-[var(--line)] bg-white/55 p-4 text-xs leading-5"><input className="mt-1 accent-[var(--teal-dark)]" type="checkbox" checked={draft.kvkk} onChange={e=>setDraft(d=>({...d,kvkk:e.target.checked}))}/><span>Kişisel verilerimin teklifin hazırlanması ve benimle iletişim kurulması amacıyla işlenmesini kabul ediyorum. Gösterilen toplamın girilen bilgilere göre hesaplandığını; ölçü veya ürün uygunluğu farklı çıkarsa teklifin revize edilebileceğini biliyorum.</span></label>{pricing&&<div className="mt-7 border-l-2 border-[var(--teal)] bg-[#edf7f4] p-4 text-sm"><strong>{draft.items.length} kalem için toplam {formatMoney(pricing.total)}</strong><br/><span className="text-xs text-[var(--ink-soft)]">KDV ve {draft.fulfilment.type==="installation"?"montaj":"kargo"} dahil.</span></div>}</>; }

function PricePanel({pricing,fulfilment,settings}:{pricing:QuotePricing|null;fulfilment:string;settings:Catalog["settings"]}) { return <aside className="h-fit border border-[var(--line)] bg-[var(--ink)] p-6 text-white shadow-[0_30px_80px_rgba(23,35,38,.18)] xl:sticky xl:top-5"><p className="mb-6 text-[9px] font-bold uppercase tracking-[.22em] text-[#78d5cf]">Canlı fiyat özeti</p>{!pricing?<><span className="text-[9px] uppercase tracking-[.16em] text-white/45">Genel toplam</span><strong className="font-display mt-1 block text-5xl font-medium text-[#78d5cf]">{formatMoney(0)}</strong><p className="mt-5 border-t border-white/10 pt-5 text-[10px] leading-5 text-white/45">Genişlik ve yüksekliği girince fiyat otomatik hesaplanır.</p></>:<><div className="space-y-4">{pricing.items.map((item,index)=><div key={item.id} className="flex justify-between gap-4 border-b border-white/10 pb-4 text-xs"><div><span className="text-white/45">{String(index+1).padStart(2,"0")}</span><strong className="ml-2">{item.label}</strong><p className="mt-1 pl-7 text-[10px] text-white/45">{item.width} × {item.height} cm · {item.quantity} adet</p></div><b>{formatMoney(item.lineTotal)}</b></div>)}</div><dl className="mt-6 space-y-3 text-xs"><Row label="Ürünler" value={formatMoney(pricing.productsSubtotal)}/><Row label={fulfilment==="installation"?"Montaj":"Kargo"} value={pricing.serviceFee===0?"Ücretsiz":formatMoney(pricing.serviceFee)}/><Row label={`KDV · %${settings.vatRate*100}`} value={formatMoney(pricing.vat)}/></dl><div className="mt-6 border-t border-white/20 pt-5"><span className="text-[9px] uppercase tracking-[.16em] text-white/50">Genel toplam</span><strong className="font-display mt-1 block text-5xl font-medium text-[#78d5cf]">{formatMoney(pricing.total)}</strong></div><p className="mt-6 text-[10px] leading-5 text-white/45">Fiyat, ölçü ve sistem uygunluğu ekibimiz tarafından doğrulandıktan sonra kesinleşir.</p></>}</aside>; }
function MobilePriceBar({pricing}:{pricing:QuotePricing|null}) { return <div className="fixed inset-x-3 bottom-3 z-50 flex items-center justify-between border border-white/10 bg-[var(--ink)] px-4 py-3 text-white shadow-[0_12px_40px_rgba(0,0,0,.38)] xl:hidden"><div><span className="block text-[8px] font-bold uppercase tracking-[.16em] text-white/45">Canlı toplam · KDV dahil</span><strong className="font-display text-3xl leading-none text-[#78d5cf]">{formatMoney(pricing?.total??0)}</strong></div><span className="max-w-24 text-right text-[8px] leading-3 text-white/40">{pricing?"Ölçünüze göre hesaplandı":"Ölçüleri girin"}</span></div>}
function Row({label,value}:{label:string;value:string}) { return <div className="flex justify-between"><dt className="text-white/50">{label}</dt><dd>{value}</dd></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label><span className="label">{label}</span>{children}</label>; }
function Choice({active,onClick,icon,title,text}:{active:boolean;onClick:()=>void;icon:React.ReactNode;title:string;text:string}) { return <button onClick={onClick} className={`p-5 text-left ${active?"bg-[var(--ink)] text-white":"border border-[var(--line)] bg-white/50"}`}><span className={active?"text-[#78d5cf]":"text-[var(--teal-dark)]"}>{icon}</span><strong className="font-display mt-5 block text-3xl">{title}</strong><span className={`mt-2 block text-xs leading-5 ${active?"text-white/55":"text-[var(--ink-soft)]"}`}>{text}</span></button>; }

function Success({reference,pricing,onReset}:{reference:string;pricing:QuotePricing;onReset:()=>void}) { const number=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||"905393165217"; const message=encodeURIComponent(`Merhaba, ${reference} numaralı teklifim hakkında görüşmek istiyorum.`); return <section id="teklif" className="technical-paper grid min-h-screen place-items-center px-4 py-20"><div className="w-full max-w-2xl border border-[var(--line)] bg-white/75 p-8 text-center shadow-[0_30px_100px_rgba(23,35,38,.12)] md:p-14"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[var(--teal-dark)] text-white"><PackageCheck size={30}/></div><p className="mt-7 text-[10px] font-bold uppercase tracking-[.22em] text-[var(--teal-dark)]">Teklif {reference}</p><h2 className="font-display mt-3 text-6xl leading-[.85]">Ölçüleriniz<br/>atölyemize ulaştı.</h2><p className="mx-auto mt-6 max-w-md text-sm leading-6 text-[var(--ink-soft)]">Toplamınız <strong className="text-[var(--ink)]">{formatMoney(pricing.total)}</strong>. Ekibimiz uygunluk ve ölçü doğrulaması için sizinle iletişime geçecek.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a className="btn-primary" href={`https://wa.me/${number}?text=${message}`} target="_blank">WhatsApp&apos;tan görüş</a><button className="btn-ghost" onClick={onReset}>Yeni teklif oluştur</button></div></div></section>; }
