import Link from "next/link";
import { ArrowRight, ArrowUpRight, Calculator, Camera, Ruler } from "lucide-react";
import { services, site } from "@/lib/site";

export function SiteFooter() {
  return <footer className="site-footer">
    <section className="footer-lead" aria-labelledby="footer-cta-title"><p className="kicker light">Ücretsiz ön değerlendirme</p><h2 id="footer-cta-title" className="font-display">Alanınızı birlikte<br/><em>değerlendirelim.</em></h2><p className="footer-lead-copy">Uygulama bölgesinin fotoğrafını gönderin, yaklaşık ölçünüzü girin; ihtiyacınıza uygun fiyat teklifini hazırlayalım.</p><ol className="footer-steps"><li><b>01</b><span className="footer-step-icon"><Camera/></span><span><strong>Fotoğrafı gönderin</strong><small>Uygulama alanını bize gösterin.</small></span><ArrowRight className="footer-step-arrow"/></li><li><b>02</b><span className="footer-step-icon"><Ruler/></span><span><strong>Ölçünüzü girin</strong><small>Yaklaşık en ve boy yeterli.</small></span><ArrowRight className="footer-step-arrow"/></li><li><b>03</b><span className="footer-step-icon"><Calculator/></span><span><strong>Teklifinizi alın</strong><small>Fiyatı inceleyip karar verin.</small></span></li></ol><Link href="/teklif-al" className="btn-light">Alanı göster, teklif al <ArrowUpRight size={17}/></Link></section>
    <div className="footer-grid"><div><b>Hizmetler</b>{services.map(s => <Link key={s.slug} href={`/hizmetler/${s.slug}`}>{s.name}</Link>)}</div><div><b>Kurumsal ve yasal</b><Link href="/kurumsal">Kurumsal</Link><Link href="/hakkimizda">Hakkımızda</Link><Link href="/sss">Sık sorulan sorular</Link><Link href="/istanbul">İstanbul hizmet bölgeleri</Link><Link href="/gizlilik">Gizlilik politikası</Link><Link href="/kvkk-aydinlatma">KVKK aydınlatma metni</Link><Link href="/cerez-politikasi">Çerez politikası</Link><Link href="/kullanim-kosullari">Kullanım koşulları</Link></div><div><b>İletişim</b><a href={`tel:${site.phone}`}>🇹🇷 +90 · {site.phoneLabel}</a><a href={`mailto:${site.email}`}>{site.email}</a><span>İstanbul, Türkiye</span></div></div>
    <div className="footer-bottom"><span>© {new Date().getFullYear()} Çalışan Yapı</span><Link href="/teklif-al">Ücretsiz keşif iste ↗</Link></div>
  </footer>;
}
