export type Campaign = {
  slug: string; serviceSlug: string; hook: string; accent: string; lead: string;
  benefits: string[]; objections: { question: string; answer: string }[];
};

export const campaigns: Campaign[] = [
  { slug:"pvc-kapi-pencere", serviceSlug:"pvc-kapi-pencere", hook:"Pencereniz yalnız kapanmasın; evi korusun.", accent:"Açılımı, camı ve montajı birlikte doğru seçin.", lead:"Açılır, çift açılım, sürme veya kaldır-sür PVC sistemini alanınızın ölçüsü, kullanım biçimi ve yalıtım beklentisine göre birlikte netleştirelim.", benefits:["20 yıllık PVC uygulama tecrübesi","Açılır, çift açılım ve sürme seçenekleri","Profil, cam, aksesuar ve montajın tek kapsamda değerlendirilmesi"], objections:[{question:"Fotoğrafla ilk değerlendirme yapılabilir mi?",answer:"Evet. Doğramanın içeriden ve dışarıdan genel görünümü ile açıklığı gösteren fotoğraflar ilk sistem önerisini hızlandırır."},{question:"Eski pencere sökümü teklife dahil mi?",answer:"Söküm, yüzey hazırlığı ve atık kapsamı mevcut doğrama keşifte görüldükten sonra yazılı teklifte açıkça belirtilir."}] },
  { slug:"cam-balkon", serviceSlug:"cam-balkon", hook:"Balkonunuz yılın çoğunda boş kalmasın.", accent:"Manzarayı kapatmadan alanı koruyun.", lead:"Katlanır veya sürme cam balkon seçimini açıklığınızın ölçüsü, kullanım biçimi ve yalıtım beklentisine göre birlikte netleştirelim.", benefits:["Tam veya kısmi açılabilen sistem seçimi","Profil, cam ve renk alternatifleri","Yerinde ölçü ve montaj koşulu kontrolü"], objections:[{question:"Fotoğrafla değerlendirme yapılabilir mi?",answer:"Evet. Alanın genel görünümü ve bağlantı yüzeylerini gösteren fotoğraflar ilk sistem önerisini hızlandırır."},{question:"Kesin fiyat hemen çıkar mı?",answer:"Kesin kapsam; ölçü, cam seçimi ve montaj yüzeyi doğrulandıktan sonra yazılı olarak hazırlanır."}] },
  { slug:"korkuluk", serviceSlug:"korkuluk", hook:"Güvenlik, manzaranın önüne geçmek zorunda değil.", accent:"Cam ve metal korkuluğu mimariye göre seçin.", lead:"Teras, balkon ve merdiven korkuluğunu taşıyıcı yüzey, kullanım alanı ve görünüm beklentisiyle birlikte değerlendirelim.", benefits:["Cam, alüminyum ve metal seçenekleri","Zemine uygun bağlantı yaklaşımı","İç ve dış mekâna göre malzeme seçimi"], objections:[{question:"Mevcut zemine uygulanabilir mi?",answer:"Taşıyıcılık ve kenar mesafeleri keşifte kontrol edilir; buna göre taban kanalı, posta veya alternatif bağlantı belirlenir."},{question:"Cam korkuluk güvenli mi?",answer:"Cam tipi, katman yapısı ve sistem detayı uygulama alanının gereksinimine göre teknik değerlendirmeyle seçilir."}] },
  { slug:"kupeste", serviceSlug:"kupeste", hook:"Merdivenin çizgisini güvenle tamamlayın.", accent:"Temiz dönüşler, sağlam bağlantılar.", lead:"Küpeşte hattını eğim, sahanlık, tutuş konforu ve iç/dış mekân koşullarına göre ölçülendirelim.", benefits:["Paslanmaz ve alüminyum seçenekleri","Kesintisiz tutamak ve dönüş planı","Merdiven ve sahanlığa özel ölçü"], objections:[{question:"Yalnız tutamak yapılabilir mi?",answer:"Evet. Duvar tipi tutamak veya mevcut korkuluk üzerine küpeşte seçenekleri alan koşuluna göre değerlendirilebilir."},{question:"Dış mekânda hangi malzeme kullanılır?",answer:"Maruziyet ve bakım beklentisine göre dış ortama uygun malzeme ve yüzey seçimi yapılır."}] },
  { slug:"asma-tavan", serviceSlug:"asma-tavan", hook:"Tavanı yalnız kapatmayın; mekânı toparlayın.", accent:"Işık, akustik ve tesisat tek düzende.", lead:"Konut ve ticari alanlarda tavan yüksekliği, aydınlatma, akustik ihtiyaç ve tesisat erişimini birlikte planlayalım.", benefits:["Alçıpan, metal, taşyünü ve baffle","Aydınlatmayla koordineli yerleşim","Bakım ve tesisat erişimi planı"], objections:[{question:"Tavan ne kadar alçalır?",answer:"Gerekli kot; taşıyıcı sistem, aydınlatma ve tesisat geçişleri görüldükten sonra belirlenir."},{question:"Tesisata erişim mümkün mü?",answer:"Modüler sistemlerde sökülebilir paneller; alçıpan uygulamalarda gerekli noktalarda müdahale kapağı planlanabilir."}] },
  { slug:"sineklik", serviceSlug:"sineklik", hook:"Pencereyi açın. Davetsiz misafirleri değil.", accent:"Kapı ve pencerenize ölçülen plise sineklik.", lead:"Açılım tipini ve kullanım sıklığını paylaşın; plise, menteşeli, sürme veya duble sistem seçeneklerini birlikte değerlendirelim.", benefits:["Kapı ve pencereye özel ölçü","Antrasit, beyaz ve ahşap tonları","Pet tülü ve güvenlik seçeneği"], objections:[{question:"Hangi model daha uygun?",answer:"Açıklık ölçüsü, kullanım sıklığı ve kapı/pencere hareketi model seçiminde belirleyicidir."},{question:"Yaklaşık ölçü yeterli mi?",answer:"İlk değerlendirme için yeterlidir; üretim öncesinde ölçülerin doğrulanması gerekir."}] },
  { slug:"kis-bahcesi", serviceSlug:"kis-bahcesi", hook:"Terasınız yalnız yazın kullanılmasın.", accent:"Işığı koruyan dört mevsimlik bir alan kurun.", lead:"Taşıyıcı yapı, çatı, cam açılımı ve yalıtım beklentisini birlikte değerlendirerek alanınıza uygun kış bahçesi çözümünü belirleyelim.", benefits:["Alana özel taşıyıcı ve çatı planı","Sabit ve açılır cam seçenekleri","Drenaj ve havalandırma değerlendirmesi"], objections:[{question:"Her terasa uygulanabilir mi?",answer:"Taşıyıcı yüzey, rüzgâr ve su tahliyesi yerinde görüldükten sonra uygun çözüm belirlenir."},{question:"Yazın çok sıcak olur mu?",answer:"Açılır camlar, gölgeleme ve hava akışı kullanım beklentisine göre birlikte planlanır."}] },
  { slug:"pergola", serviceSlug:"pergola", hook:"Güneş çıktığında kaçmayın, gölgeyi yönetin.", accent:"Terasınıza ölçülen açılır pergola.", lead:"Açıklığı, eğimi, su tahliyesini ve motor seçimini birlikte değerlendirerek teras veya bahçenize uygun sistemi planlayalım.", benefits:["Manuel ve motorlu alternatifler","Yağmur tahliyesi ve eğim planı","Konut ve ticari alana özel ölçü"], objections:[{question:"Yağmurda kullanılabilir mi?",answer:"Sistem, kumaş ve drenaj doğru seçildiğinde yağmur kontrolü sağlanabilir."},{question:"Elektrik hazırlığı gerekir mi?",answer:"Motorlu sistemlerde hat ve kontrol konumu keşif sırasında belirlenir."}] },
  { slug:"giyotin-cam", serviceSlug:"giyotin-cam", hook:"Manzarayı kapatmadan rüzgârı kontrol edin.", accent:"Tek dokunuşla açılan motorlu cam sistemi.", lead:"Panel düzenini, motoru, bağlantı yüzeyini ve elektrik hazırlığını açıklığınıza göre birlikte netleştirelim.", benefits:["Dikey hareketle alan tasarrufu","Motor ve kumanda seçenekleri","Konut ve ticari açıklıklara özel ölçü"], objections:[{question:"Güvenli mi?",answer:"Panel, motor ve kontrol detayları kullanım alanına göre teknik olarak değerlendirilir."},{question:"Korkuluk olarak kullanılabilir mi?",answer:"Uygun ürün ve proje koşullarında sabit alt panel bu amaçla değerlendirilebilir."}] },
];
export function getCampaign(slug:string){return campaigns.find(c=>c.slug===slug)}
