import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowDown, Check } from "lucide-react";
import { ServiceRequestForm } from "@/components/ServiceRequestForm";
import { campaigns, getCampaign } from "@/lib/campaigns";
import { getService } from "@/lib/site";

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return campaigns.map(({slug})=>({slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const campaign=getCampaign((await params).slug);if(!campaign)return{};const service=getService(campaign.serviceSlug)!;return{title:`${service.name} Keşif Kampanyası`,description:campaign.lead,robots:{index:false,follow:true},openGraph:{title:campaign.hook,description:campaign.accent,images:[service.image]}}}

export default async function CampaignPage({params}:Props){const campaign=getCampaign((await params).slug);if(!campaign)notFound();const service=getService(campaign.serviceSlug)!;return <main className="bg-[var(--paper)]">
  <section className="relative min-h-[92svh] overflow-hidden bg-[var(--ink)] text-white"><Image src={service.image} alt={`${service.name} uygulama örneği`} fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#10191b] via-[#10191b]/55 to-[#10191b]/15"/><div className="relative z-10 mx-auto flex min-h-[92svh] max-w-[1500px] flex-col justify-between px-5 py-7 sm:px-8 lg:px-[7vw] lg:py-12"><div className="flex items-center justify-between border-b border-white/20 pb-5"><Image src="/brand/umayapi-logo-header.webp" alt="Uma Yapı" width={900} height={160} className="h-auto w-48 brightness-0 invert sm:w-60"/><span className="text-[9px] font-bold tracking-[.16em] text-white/60 uppercase">Instagram’a özel keşif sayfası</span></div><div className="max-w-5xl py-16"><p className="mb-5 text-[10px] font-bold tracking-[.18em] text-[#7ee4dd] uppercase">İstanbul · {service.name}</p><h1 className="font-display text-5xl leading-[.85] font-medium tracking-[-.045em] sm:text-7xl lg:text-[7rem]">{campaign.hook}<br/><em className="font-normal text-[var(--teal)]">{campaign.accent}</em></h1><p className="mt-8 max-w-2xl text-sm leading-7 text-white/70 sm:text-base">{campaign.lead}</p><a href="#teklif" className="mt-9 inline-flex min-h-14 items-center gap-8 bg-[var(--teal)] px-6 text-xs font-bold tracking-[.08em] text-[var(--ink)] uppercase">Fotoğraf gönder, teklif iste <ArrowDown size={18}/></a></div></div></section>
  <section className="mx-auto grid max-w-[1500px] grid-cols-1 gap-12 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:gap-24 lg:px-[7vw] lg:py-28"><div><p className="kicker">Neden bu sistem?</p><h2 className="font-display text-5xl leading-[.9] font-medium tracking-[-.04em] sm:text-6xl">Karar vermeden<br/><em className="font-normal text-[var(--teal)]">önce netleşsin.</em></h2></div><div className="flex flex-col justify-center gap-4">{campaign.benefits.map(item=><div key={item} className="flex items-center gap-4 border-b border-[var(--line)] py-4 text-sm"><Check size={18} className="text-[var(--teal-dark)]"/>{item}</div>)}</div></section>
  <section className="bg-[var(--paper-deep)] px-5 py-20 sm:px-8 lg:px-[7vw] lg:py-28"><div className="mx-auto grid max-w-[1500px] grid-cols-1 gap-8 lg:grid-cols-2">{campaign.objections.map(item=><article key={item.question} className="border border-[var(--line)] bg-[var(--paper)] p-7 sm:p-10"><h2 className="font-display text-3xl font-medium sm:text-4xl">{item.question}</h2><p className="mt-5 text-sm leading-7 text-[var(--ink-soft)]">{item.answer}</p></article>)}</div></section>
  <section id="teklif" className="pt-20 lg:pt-28"><div className="mx-auto max-w-[1500px] px-5 sm:px-8 lg:px-[7vw]"><p className="kicker">Ücretsiz ön değerlendirme</p><h2 className="font-display mb-12 text-5xl leading-[.9] font-medium tracking-[-.04em] sm:text-7xl">Alanınızı anlatın,<br/><em className="font-normal text-[var(--teal)]">biz sizi arayalım.</em></h2></div><ServiceRequestForm initialService={service.slug}/></section>
  <div className="bg-[var(--ink)] px-5 py-7 text-center text-[10px] tracking-[.12em] text-white/45 uppercase"><Link href="/">Uma Yapı ana sayfasına dön</Link></div>
 </main>}
